### ISSUE TITLE
Core Java 

### ISSUE THREAD

**Issue by prashantkalokhe** [prashantkalokhe/Hactoberfest-2022-New#11]

**Comment by prashantkalokhe** [comment]
> _No description provided._

Basic java codes

**Comment by siddhesh-coder** [comment]
assign me this issue

**Comment by Aditya-Harsh** [comment]
Hi there,
I have experience working in this domain and would love to work on this issue.
Please assign it to me.

**Comment by prashantkalokhe** [comment]
Assigned Aditya
