### ISSUE TITLE
Matrix multiplication program

### ISSUE THREAD

**Issue by PushkarMishra15** [prashantkalokhe/Hactoberfest-2022-New#118]
program of matrix multiplication in cpp

**Comment by PushkarMishra15** [comment]
I would be glad if you would assign me this task.

**Comment by Pragya2056** [comment]
Please assign this to me!!

**Comment by PushkarMishra15** [comment]
hey @prashantkalokhe, please assign this task to me

**Comment by AnshShah77** [comment]
i can do this, can u assign it to me?

**Comment by ChandniJha630** [comment]
I would like to solve this issue in all programming languages i.e, c,c++,python,java. Please assign this issue to me

**Comment by Pragya2056** [comment]
This issue was looked at in #120

**Comment by Pragya2056** [comment]
@prashantkalokhe 
please review it.

**Comment by prashantkalokhe** [comment]
I java developer so add more java project/ code

**Comment by Pragya2056** [comment]
@prashantkalokhe 
I have submitted CPP program in #120 
Please review

**Comment by AnshShah77** [comment]
i hv submitted, please review
its my first time in hacktober i need confidence from u all

**Comment by amanaggarwal06** [comment]
Hey, please assign it to me.
I want to contribute.

**Comment by prashantkalokhe** [comment]
Java
