### ISSUE TITLE
Current Date Time using Python

### ISSUE THREAD

**Issue by RitwikGanguly** [prashantkalokhe/Hactoberfest-2022-New#126]
Have to show current date, time(e.g. day, month, year, minute, second etc)

**Comment by RitwikGanguly** [comment]
@prashantkalokhe please Assign me in this issue

**Comment by chandrabosep** [comment]
> @prashantkalokhe please Assign me in this issue

Its open for everyone brother

**Comment by RitwikGanguly** [comment]
Thanks for assigning me @prashantkalokhe 
please check out my pr of this issue in pr no - #143

**Comment by RitwikGanguly** [comment]
And review and merge it if possible

**Comment by prashantkalokhe** [comment]
Java
