### ISSUE TITLE
HTML CSS JAVASCRIPT 

### ISSUE THREAD

**Issue by prashantkalokhe** [prashantkalokhe/Hactoberfest-2022-New#14]

**Comment by dishantzaveri** [comment]
Can you please assign me the task?

**Comment by Ramubethi** [comment]
Can you please assign me the task?

**Comment by pratyushkr11** [comment]
Can you please assign me this issue. I want to add a project.

**Comment by prashantkalokhe** [comment]
> Can you please assign me this issue. I want to add a project.

Assigned

**Comment by Ramubethi** [comment]
Added Number Guess Game Project

**Comment by Rachana1104** [comment]
Can you please assign this issue to me. I would like to add a project

**Comment by Aryan-Bhatt-pro** [comment]
Hi, can I contribute my Javascript project here? Thanks

**Comment by prashantkalokhe** [comment]
Contribute

**Comment by Aryan-Bhatt-pro** [comment]
> Contribute

Hi, have added the project, please see the PR

**Comment by debjitnandan05** [comment]
I want to contribute my HTML, CSS, and js project to your repository. Can you please assign me

**Comment by mtahashahid** [comment]
hey @prashantkalokhe I want to add a project can you please assign this to me.

**Comment by EngineerAditijain** [comment]
Sir please assign this task to me

**Comment by PRO-BROS** [comment]
I also faced a similar issue on my [site](https://prhocoding.com/) but thankfully I hire a developer which resolve that's issue.

**Comment by prashantkalokhe** [comment]
Added
