### ISSUE TITLE
Imporve readme.md file

### ISSUE THREAD

**Issue by prashantkalokhe** [prashantkalokhe/Hactoberfest-2022-New#145]
Add new animation
New graphics

**Comment by super-duper-sp** [comment]
please, assign me this issue. I would like to work on this.

**Comment by shrishti147** [comment]
please assign this to me.

**Comment by Ashish93-mrx** [comment]
I would like to add Banner and graphs stats, please assign this issue to me.

**Comment by sanvi1803** [comment]
please assign me this issue ill fix this
