### ISSUE TITLE
C

### ISSUE THREAD

**Issue by prashantkalokhe** [prashantkalokhe/Hactoberfest-2022-New#18]
C codes project in C

**Comment by ujwxl23** [comment]
please assign me this under hacktoberfest-2022

**Comment by ChandniJha630** [comment]
Please assign this issue to me. I have project of telephone directory using singly linked list in C. I would like to contribute in this under label of hactober 2022

**Comment by ujwxl23** [comment]
I can contribute code regarding the operations in array, linked list, stack, queue, trees, binary tress.
Assign me under Hacktober-fest 2022.

**Comment by prashantkalokhe** [comment]
Assigned upload

**Comment by ujwxl23** [comment]
I have uploaded some programs in c about linked list and binary search. Please look into it and accept my contribution under hacktober fest 2022.
Created a folder called c programs to upload all the programs.
