### ISSUE TITLE
is this repo still there in hacktoberfest?

### ISSUE THREAD

**Issue by pratikroy107** [prashantkalokhe/Hactoberfest-2022-New#188]

**Comment by MidhaShrey** [comment]
i think its not there it is now excluded

**Comment by prashantkalokhe** [comment]
No

**Comment by prashantkalokhe** [comment]
No

**Comment by KRRISHSINGH08** [comment]
yes it is excluded as my PR wernt accepted showing repo got excluded !

**Comment by prashantkalokhe** [comment]
Yes contribute in new repository
With same or different projects

Last 4 day Hactoberfest name repo
