### ISSUE TITLE
C++

### ISSUE THREAD

**Issue by prashantkalokhe** [prashantkalokhe/Hactoberfest-2022-New#19]
Project codes in c++

**Comment by dishantzaveri** [comment]
Please assign it to me and let me know what exactly has to be done

**Comment by sharvarii11** [comment]
hey @prashantkalokhe ,what exactly we has to do to contribute.

**Comment by srdhal** [comment]
@prashantkalokhe Please assign it to me . I also want to work on this issue.

**Comment by prashantkalokhe** [comment]
How to participate in Hacktoberfest: 1. Register to Hacktoberfest.

2. Find the open-source project accepted by Hacktoberfest. 3. Fork the repository.

4. Clone the repository. 5. Contribute to the open source.

6. Push your contribution.

50

7. Create a pull request. 8. Wait for the maintainer to merge your

changes. 9. After the maintainer approved your

changes, then wait for 7 days to get all 4 PR accepted by the Hacktoberfest team.

**Comment by Anshul-9923** [comment]
Hi, @prashantkalokhe I have create a PR.
Please take a look.
Link: https://github.com/prashantkalokhe/Hactoberfest-2022-New/pull/27

**Comment by sanvi1803** [comment]
Please assign me this issue... I want to write this code.

**Comment by mtahashahid** [comment]
Hi, @prashantkalokhe I want to contribute.
Can you please assign this to me?

**Comment by Nikita0509** [comment]
plzzz assign this issue to me under hacktoberfest 2022

**Comment by ChandniJha630** [comment]
plzzz assign this issue to me under hacktoberfest 2022

**Comment by prashantkalokhe** [comment]
Please make java submission
