### ISSUE TITLE
Python codes /projects

### ISSUE THREAD

**Issue by prashantkalokhe** [prashantkalokhe/Hactoberfest-2022-New#20]

**Comment by dishantzaveri** [comment]
Please assign it to me and let me know what exactly has to be done

**Comment by Nikita0509** [comment]
plz assign this project to me under hacktoberfest 2022

**Comment by C-V-Anish** [comment]
I would love to contribute, Please assign me this issue @prashantkalokhe

**Comment by KRRISHSINGH08** [comment]
Please assign me this issue

**Comment by prashantkalokhe** [comment]
> Please assign me this issue

Assigned

**Comment by MSVelan** [comment]
Sir, I would like to contribute to this project. Can you please assign it to me?

**Comment by prashantkalokhe** [comment]
Add project/codes
