### ISSUE TITLE
Factorial in cpp

### ISSUE THREAD

**Issue by PushkarMishra15** [prashantkalokhe/Hactoberfest-2022-New#38]
i want to add factorial program in cpp

**Comment by PushkarMishra15** [comment]
I would be glad if you can assign this task to me

**Comment by kashish0604** [comment]
hey @prashantkalokhe can you assign this issue to me i can work on it

**Comment by KRRISHSINGH08** [comment]
please assign this to me

**Comment by prashantkalokhe** [comment]
> please assign this to me

Assigned

**Comment by kashish0604** [comment]
hey @PushkarMishra15 i have added PR to this issue kindly accept it Please

**Comment by ChandniJha630** [comment]
Please assign this issue to me under label of hactoberfest 2022

**Comment by prashantkalokhe** [comment]
Contribute in Java

**Comment by prashantkalokhe** [comment]
Java project
