### ISSUE TITLE
Java project/codes/DSA in java

### ISSUE THREAD

**Issue by prashantkalokhe** [prashantkalokhe/Hactoberfest-2022-New#66]

**Comment by Sathasivamthirumoorthi** [comment]
please assign this to me

**Comment by SheriffAbdullah** [comment]
Dear @prashantkalokhe, kindly assign this to Me.

**Comment by Purvi-sai** [comment]
I would like to contribute in this issue. Please assign this to me.

**Comment by prashantkalokhe** [comment]
Add project in java if possible

**Comment by Rachana1104** [comment]
Please assign this issue to me. I would like to add a project

**Comment by sejal-phatangare** [comment]
sejal phatangare
cummins college of engineering, pune
please assign me this issue

**Comment by prashantkalokhe** [comment]
> sejal phatangare cummins college of engineering, pune please assign me this issue

Assigned

**Comment by Dishu099** [comment]
Can I add java linked list ques in this repository @prashantkalokhe

**Comment by Dishu099** [comment]
I have added an java code to reverse the linked list please checkout my PR.

**Comment by Dishu099** [comment]
@prashantkalokhe can you please check my PR

**Comment by SheriffAbdullah** [comment]
PR done, Contributor. Thank you for the opportunity.
