### ISSUE TITLE
Rotten orange ||best solution with explanation

### ISSUE THREAD

**Issue by SHOBHA-0502** [prashantkalokhe/Hactoberfest-2022-New#96]
I would like to add the famous Rotting Oranges problem along with its detailed implementation and demo. 

@prashantkalokhe  Please assign this issue to me in hacktoberfest .
![image](https://user-images.githubusercontent.com/93420160/197322836-7c30c728-8fde-46e8-aab1-a76d13dd9c67.png)

**Comment by HarshAggarwal1** [comment]
hey can you assign me this?

**Comment by prashantkalokhe** [comment]
Upload codes bro
